openapi: 3.1.0
info:
  title: A minimal OpenAPI document
  description: |
    This API is just example.
    Basic CRUD endpoints
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /users:
    get:
      tags:
        - identity
      summary: Get all users.
      description: Returns an array of User model
      parameters: []
      responses:
        '200':
          description: A JSON array of User model
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/User'
                example:
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jane Doe
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
tags:
  - name: identity
    description: Identity microservice