version: "3.9"
services:
  web:
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web:/usr/src/app 
      # use node_modules in container
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  sales:
    container_name: sales
    build:
      context: ./sales
    volumes:
      - ./sales:/app 
    ports:
      - "8080:8080"
    tty: true