version: "3.9"
services:
  web:
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web:/usr/src/app 
      # use node_modules in container
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  sales:
    container_name: sales
    build:
      context: ./sales
    volumes:
      - ./sales:/app 
    ports:
      - "8080:8080"
    tty: true
  sales-db:
    image: postgres:14.2
    container_name: sales-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant1
      POSTGRES_PASSWORD: J3fYk*u~
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - sales-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.5
    container_name: pgadmin
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: Df8Bj(~g
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - sales-db
volumes:
  sales-db:
  pgadmin: