on:
  push:
    branches:
      - "**"
      - "!main"
env:
  MREMAID_CI_CACHE_PATH: mermaid-ci-image
  NERMAID_CI_VERSION: 8.13.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Cache mermaid-cli docker image
        id: cache-mermaid-cli
        uses: actions/cache@v2
        with:
         path: ${{ env.MREMAID_CI_CACHE_PATH }}
         key: ${{ runner.os }}-mermaid-cli-${{ env.NERMAID_CI_VERSION }}
      - name: Pull and save mermaid cli docker image
        if: steps.cache-mermaid-cli.outputs.cache-hit != 'true'
        run: |
          docker pull minlag/mermaid-cli:${NERMAID_CI_VERSION}
          docker save minlag/mermaid-cli:${NERMAID_CI_VERSION} -o ${MREMAID_CI_CACHE_PATH}
      - run: docker load -i ${MREMAID_CI_CACHE_PATH}
      - name: generate mermaid image
        run: |
          docker run -v $GITHUB_WORKSPACE/docs/design:/data minlag/mermaid-cli:${NERMAID_CI_VERSION} -i /data/index.template.md -o /data/index.md
      - name: git setting
        run: |
          git config --local user.email "shintaro.a.uchiyama@gmail.com"
          git config --local user.name "shintaro-uchiyama"
      - name: Commit files
        run: |
          git add .
          git commit -m "feat(docs): generate mermaid image" -a
          git pull
          git push origin ${{github.head_ref}}
