on:
  push:
    branches:
      - "**"
      - "!main"
env:
  LOCALSTACK_CACHE_PATH: localstack-image
  LOCALSTACK_VERSION: 0.1.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Cache a LocalStack Docker image
        id: cache-localstack
        uses: actions/cache@v2
        with:
         path: ${{ env.LOCALSTACK_CACHE_PATH }}
         key: ${{ runner.os }}-localstack-${{ env.LOCALSTACK_VERSION }}
      - name: Pull and save a LocalStack Docker image
        if: steps.cache-localstack.outputs.cache-hit != 'true'
        run: |
          docker pull localstack/localstack:${LOCALSTACK_VERSION}
          docker save localstack/localstack:${LOCALSTACK_VERSION} -o ${LOCALSTACK_CACHE_PATH}
      - run: docker load -i ${LOCALSTACK_CACHE_PATH}
      - name: generate mermaid image
        run: |
          docker pull minlag/mermaid-cli:8.13.10
          docker run -v $GITHUB_WORKSPACE/docs/design:/data minlag/mermaid-cli -i /data/index.template.md -o /data/index.md
      - name: git setting
        run: |
          git config --local user.email "shintaro.a.uchiyama@gmail.com"
          git config --local user.name "shintaro-uchiyama"
      - name: Commit files
        run: |
          git add .
          git commit -m "feat(docs): generate mermaid image" -a
          git pull
          git push origin ${{github.head_ref}}
